service: flickrgroupaddr-api-aws-us-east-2

frameworkVersion: '3'

configValidationMode: error


provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  memorySize: 512
  environment:
    PGSQL_DB_INFO_SSM_PATH: "/flickrgroupaddr/resources/pgsql/creds"
    SNS_TOPIC_ARN: !Ref fgaAttemptAddTopic
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
            - "ssm:GetParameters"
            - "ssm:PutParameter"
          Resource: "arn:aws:ssm:us-east-2:293119271420:parameter/flickrgroupaddr/*"

        - Effect: "Allow"
          Action:
            - "SNS:Publish"
          Resource: !Ref fgaAttemptAddTopic

  httpApi:
    cors: 
      allowedOrigins:
        - "https://flickrgroupaddr.com"

functions:
  api-new-request:
    handler: fga_rest_api_handler.create_new_fga_request
    events:
      - httpApi:
          path: /api/v001/fga_request
          method: post

  flickr-attempt-add:
    handler: flickr-proxy.attempt_flickr_group_add
    events:
      - sns:
          arn: !Ref fgaAttemptAddTopic
          topicName: AttemptFlickrGroupAdd

resources: 
  Resources:
    fgaAttemptAddTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: AttemptFlickrGroupAdd
      
	
plugins:
  - serverless-python-requirements
 
custom:
  pythonRequirements:
    dockerizePip: true
